// AUTO-GENERATED by scripts/copy-rule-pdfs.mjs — НЕ редактировать вручную.
// Источник: rules/*.pdf. Пересборка: npm run rules:pdf
export const ruleOriginalPdfs: Record<string, string> = {
  "obschie": "/rules/obschie.pdf",
  "economy": "/rules/economy.pdf",
  "alchemy": "/rules/alchemy.pdf",
  "smithing": "/rules/smithing.pdf",
  "gardening": "/rules/gardening.pdf",
  "faith": "/rules/faith.pdf",
  "enchanting": "/rules/enchanting.pdf"
}
